### PR TITLE
Typos: Dictionary\ on code-example-authentication-oauth.md

### PR DESCRIPTION
**Pull request by sweetlapeet**
fixed two methods containing typos

### CODE REVIEW

**Comment by eric-urban** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingAds/shopping-content/code-example-authentication-oauth.md](https://github.com/sweetlapeet/BingAds-docs/blob/patch-2/BingAds/shopping-content/code-example-authentication-oauth.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C11%5C20%5Ca2e0ab55-2284-a03f-0fb2-0350b6c468ba%5CPullRequest%5C201811202158066374-456%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Qkex6yHuOODatZEApYmyD%2BpND%2FPOspIxXxm4XYSdw5Q%3D&st=2018-11-20T21%3A54%3A38Z&se=2018-12-21T21%3A59%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by swhite-msft** [comment]
@sweetlapeet, thanks for pointing out the issue. Have you signed a CLA? Unfortunately, we can't merge the request without it.

**Comment by sweetlapeet** [comment]
I have not signed the CLA. Where can I go to sign it?

Regards, 
Aharon Najafi

**Comment by swhite-msft** [comment]
We've checked and it turns out that because the change is minor, a CLA is not required. 

"Minor corrections or clarifications to documentation and code examples in public repositories are covered by the docs.microsoft.com Terms of Use. New or significant changes generate a comment in the pull request, asking you to submit an online Contribution License Agreement (CLA) if you are not an employee of Microsoft. We need you to complete the online form before we can review or accept your pull request."

Reference: https://docs.microsoft.com/en-us/contribute/.

But it looks like the change is against live instead of master. To make things easy, we're going to go ahead and make your changes in master as part of other updates.

We appreciate your partnership and look forward to working with you in the future.


https://docs.microsoft.com/en-us/contribute/

**Comment by eric-urban** [comment]
@sweetlapeet sorry for the delay. This has already been updated. Thanks!

**Pull request closed without merging**
